In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('E:\\pycharm项目\\data_analysis\\data\\23 L2W1-优衣库数据.csv')
df

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
0,658,深圳,线下,Female,25-29,Weekday,当季新品,4,796.0,4,4,59
1,146,杭州,线下,Female,25-29,Weekday,运动,1,149.0,1,1,49
2,70,深圳,线下,Male,>=60,Weekday,T恤,2,178.0,2,2,49
3,658,深圳,线下,Female,25-29,Weekday,T恤,1,59.0,1,1,49
4,229,深圳,线下,Male,20-24,Weekend,袜子,2,65.0,2,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...
22288,146,杭州,线下,Female,30-34,Weekday,短裤,1,80.0,1,2,19
22289,430,成都,线下,Female,25-29,Weekend,T恤,1,79.0,1,1,49
22290,449,武汉,线下,Female,35-39,Weekday,T恤,1,158.0,1,2,49
22291,758,杭州,线下,Female,20-24,Weekday,袜子,1,26.0,1,1,9
22292,616,成都,线下,Male,30-34,Weekday,当季新品,1,79.0,1,1,59

# 1.分组聚合

-       df对象.groupby(['分组字段1', '分组字段2', ...]).get_group(('列名1', '列名2', ...))

！！！ 细节1：group()中是用[]包裹，而get_group()中是用()包裹

！！！ 细节2：前面group()中有多少个列名，则后面get_group()中就要提供多少信息

-       df对象.groupby(['分组字段1', '分组字段2', ...]).agg({
            '列名1':'函数名1',
            '列名2':'函数名2',
            ...
            })

！！！ 细节1：函数名 -> 不加()

！！！ 细节2：可以是相同草组0哦，也可以是不同操作

In [6]:
# 1.1 按照单列分组
df.groupby('city')

In [7]:
# 按照两列分组
df.groupby(['city', 'channel'])

In [8]:
# 获得分组后某个组的数据
df.groupby(['city', 'channel']).get_group(('北京', '线下'))

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
9,21,北京,线下,Female,45-49,Weekend,毛衣,1,199.00,1,1,99
168,21,北京,线下,Female,35-39,Weekday,毛衣,3,447.00,3,3,99
175,21,北京,线下,Female,45-49,Weekend,配件,1,149.00,1,1,29
263,21,北京,线下,Male,20-24,Weekday,T恤,1,55.33,1,1,49
289,21,北京,线下,Female,35-39,Weekend,牛仔裤,1,199.00,1,1,69
...,...,...,...,...,...,...,...,...,...,...,...,...
22037,21,北京,线下,Female,20-24,Weekday,T恤,7,493.00,7,7,49
22110,21,北京,线下,Male,50-54,Weekend,当季新品,1,79.00,1,1,59
22192,21,北京,线下,Female,20-24,Weekday,T恤,7,693.00,7,7,49
22273,21,北京,线下,Female,20-24,Weekday,当季新品,2,288.00,2,2,59
22280,21,北京,线下,Female,35-39,Weekend,T恤,1,59.00,1,1,49

In [9]:
# 分组 + 聚合
# 场景1：通过 城市 和 销售渠道 分组，对 销售金额 计算其总和
df.groupby(['city', 'channel']).agg({
    'revenue':'sum'
    })

# 场景2：通过 城市 和 销售渠道 分组，分别对 销售金额计算其总和 + 成本计算其平均值
df.groupby(['city', 'channel']).agg({
    'revenue':'sum',
    'unit_cost':'mean'
    })

                revenue  unit_cost
city channel
上海   线上       114438.09  45.868852
     线下       275383.64  46.243122
北京   线下       130458.62  45.343154
南京   线下       123150.93  46.280000
广州   线上       200893.30  45.554622
     线下       117231.19  46.747440
成都   线下       208189.86  47.116416
杭州   线下       589518.49  45.824306
武汉   线上       281420.73  44.517685
     线下       308357.05  46.649105
深圳   线下       733123.68  46.179193
西安   线上        30088.01  43.786325
     线下       180686.61  47.023341
重庆   线上        26330.35  44.109890
     线下       237162.30  46.763240

# 2. 分组过滤

-       df对象.groupby(['分组字段1', '分组字段2', ...]).filter(
            lambda x: dosomething return True/False
            )

！！！ 细节1：此处x指的是除了 城市 和 销售渠道 的其他全部列

In [ ]:
# 2.1 分组 + 过滤
# 场景：通过 城市 ，过滤出 销售金额 > 200 的数据
df.groupby('city').filter(lambda x : x['revenue'].mean() > 200)
# df.groupby('city').filter(lambda x : x.revenue.mean() > 200).city.drop_duplicates()
# df.groupby('city').filter(lambda x : x.revenue.mean() > 200).city.unique()